chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    if (request.action === 'fillFields') {
        var inputFields = document.getElementsByTagName('input');
        for (var i = 0; i < inputFields.length; i++) {
            var input = inputFields[i];
            if (input.type === 'text') {
                var things = [
                    "Dream big",
                    "Stay strong",
                    "Embrace change",
                    "Find joy",
                    "Inspire others",
                    "Be fearless",
                    "Spread love",
                    "Seek adventure",
                    "Create happiness",
                    "Chase dreams",
                    "Celebrate life",
                    "Stay focused",
                    "Find purpose",
                    "Love deeply",
                    "Explore possibilities",
                    "Embrace challenges",
                    "Inspire greatness",
                    "Keep learning",
                    "Believe in yourself",
                    "Take risks",
                    "Live fully",
                    "Follow your heart",
                    "Enjoy simplicity",
                    "Choose happiness",
                    "Seek balance",
                    "Make memories",
                    "Embrace uniqueness",
                    "Find peace",
                    "Create magic",
                    "Stay positive",
                    "Celebrate success",
                    "Find beauty",
                    "Ignite passion",
                    "Conquer fears",
                    "Appreciate moments",
                    "Unlock potential",
                    "Live passionately",
                    "Dream boldly",
                    "Stay humble",
                    "Spark creativity",
                    "Find inspiration",
                    "Love fiercely",
                    "Embrace possibilities",
                    "Keep exploring",
                    "Rise above",
                    "Spread kindness",
                    "Find strength",
                    "Savor life",
                    "Create art",
                    "Stay curious",
                    "Find balance",
                    "Seek happiness",
                    "Embrace solitude",
                    "Inspire change",
                    "Love unconditionally",
                    "Dream fearlessly",
                    "Stay motivated",
                    "Find purpose",
                    "Celebrate diversity",
                    "Explore the unknown",
                    "Embrace the journey",
                    "Inspire others",
                    "Be resilient",
                    "Spread positivity",
                    "Seek adventure",
                    "Create memories",
                    "Cherish love",
                    "Stay present",
                    "Believe in magic",
                    "Take action",
                    "Live authentically",
                    "Follow your passion",
                    "Enjoy the ride",
                    "Choose wisely",
                    "Seek wisdom",
                    "Make a difference",
                    "Embrace imperfection",
                    "Find your voice",
                    "Love yourself",
                    "Dream, believe",
                    "Stay grateful",
                    "Spark joy",
                    "Find purpose",
                    "Celebrate uniqueness",
                    "Inspire dreams",
                    "Keep growing",
                    "Embrace possibilities",
                    "Love deeply",
                    "Seek happiness",
                    "Create miracles",
                    "Stay inspired",
                    "Find harmony",
                    "Spread laughter",
                    "Seek adventures",
                    "Chase sunsets"
                ];
                let val = things[Math.floor(Math.random()*things.length)];
                input.value = val;

            }
        }
    }
});